/* adding custom product info on the edit product page */
.wp-core-ui .woocommerce_variations .woocommerce_variation .wwcAmzAff_asin {
    margin-top: 8px;
}
.wp-core-ui .wwcAmzAff_asin_field a.button.button-primary {
    display: inline-block;
    margin-left: 7px;
}

/* adding custom product info on the product listing page */
th#wwcAmzAff_product_info { 
	width: 170px; 
}
	td.wwcAmzAff_product_info .wwcAmzAffWoocustomFields span:first-child {
	    color: green;
	    font-weight: bold;
	    font-size: 14px;
	    vertical-align: bottom;
	}
	td.wwcAmzAff_product_info .wwcAmzAffWoocustomFields a {
	    vertical-align: bottom;
	    margin-left: 4px;
	}
	td.wwcAmzAff_product_info .wwcAmzAffWoocustomFields span:last-child {
	    vertical-align: bottom;
	    margin-left: 8px;
	}
